---
test:
  chain_id: cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f
  node_endpoint: http://localhost:7777
  accounts_manager: accntmngr
  funds_manager: fundsmngr
  ram_manager: rammngr

  accounts:
    test:
      auth:
        owner:
          permissions:
            - EOS6z98haKv12d8vAJbDUkXmpK3PaKvf3Dv1NApo9MCxJ8oNWssDi
        active:
          # parent: owner # implicit for active
          threshold: 2
          permissions:
            - EOS5nYs7LDcFcVtFmnYrhYQv9Z8DPDd1r4MJ8na2MvcPPJkXwzM3x
            - dapptoken@eosio.code 1
            - wait@600 1
      ram: 262144 # 256KB of RAM
      # stake resources to self
      cpu:
        - delegate_to: test
          amount: 1e6
      net:
        - delegate_to: test
          amount: 1200000
      tokens:
        - account: eosio.token
          amount: 100.0000 EOS
      code: examples/contracts/hello/hello.wasm
      abi: examples/contracts/hello/hello.abi